spring.application.name=to-do-app

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=toDoDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

server.error.include-message=always
server.error.include-binding-errors=always

spring.mail.host=smtp.gmail.com
#tls-po siguren protokol ot ssl
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.file.name=logs/app.log