spring.application.name=to-do-app

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=toDoDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect